/*
 * ascii.rest/kit: tools for making ascii art of your own, as pieces that play
 * wherever the library's do. Part of ascii.rest by @bas3line
 * (https://github.com/bas3line), MIT licensed.
 *
 *   import { TAU, field } from "ascii.rest/kit";
 *
 *   export default field({ name: "sea", ramp: "blocks", colors: ["#0b3d91", "#7fdbff"], period: 2 },
 *     (x, y, t, at) => 0.5 + 0.5 * Math.sin(x * 6 + y * 2 + TAU * at.phase));
 */

// The grid, the piece() builder, colours, ramps and the maths every module shares.
export {
  EMPTY,
  INK,
  MAX,
  NONE,
  Palette,
  Surface,
  TAU,
  and,
  asPiece,
  bayer,
  checkMeta,
  clamp,
  code,
  fail,
  fract,
  gradient,
  hash,
  hex,
  isHex,
  lerp,
  mergePalettes,
  metaOf,
  mix,
  mulberry32,
  nearest,
  piece,
  ramp,
  ramps,
  rgb,
  sample,
  shadeChar,
  smoothstep,
  snapshot,
  specOf,
  spread,
  valueNoise,
  type Color,
  type Context,
  type Draw,
  type KitPiece,
  type MakerSpec,
  type PaletteSpec,
  type PieceSpec,
  type RampName,
  type Region,
  type Sampler,
  type Setup,
  type Source,
  type Themed,
} from "./core.ts";

// Noise, randomness, easing, time and 3D maths.
export {
  camera,
  cycle,
  degrees,
  ease,
  fbm,
  fbm3,
  invLerp,
  lcm,
  loopNoise,
  mod,
  noise,
  noise2,
  noise3,
  noise4,
  oscillate,
  phase,
  pingpong,
  progress,
  project,
  pulse,
  radians,
  random,
  remap,
  ridged,
  rotate3,
  rotation,
  scatter,
  step,
  triangle,
  tween,
  twinkle,
  valueNoise3,
  vec2,
  vec3,
  worley,
  wrap,
  type Camera,
  type CameraOptions,
  type EaseName,
  type FbmOptions,
  type LoopNoiseOptions,
  type Noise,
  type NoiseKind,
  type NoiseOptions,
  type Projected,
  type Projection,
  type Random,
  type ScatterOptions,
  type Spot,
  type TweenOptions,
  type TwinkleOptions,
  type Vec2,
  type Vec3,
  type View,
  type WorleyOptions,
} from "./math.ts";

// Drawing on the grid: text, lines, boxes, shapes, stamps, braille and half-block canvases.
export {
  arc,
  around,
  boxes,
  braille,
  circle,
  ellipse,
  label,
  line,
  pixels,
  polygon,
  polyline,
  ray,
  rect,
  stamp,
  text,
  type Align,
  type BoxStyle,
  type Braille,
  type LineOptions,
  type Pixels,
  type PlotOptions,
  type Point,
  type PolygonOptions,
  type RectOptions,
  type ShapeOptions,
  type SpriteOptions,
  type StampOptions,
  type TextOptions,
  type VAlign,
} from "./draw.ts";

// Ascii art from a formula of x, y and t.
export { drawField, field, type FieldCell, type FieldFn, type FieldOptions, type FieldSpec } from "./field.ts";

// 3D scenes: shapes, a camera, light and textures.
export {
  cone,
  cube,
  cylinder,
  group,
  lines,
  mesh,
  orbit,
  parametric,
  plane,
  points,
  render3d,
  scene,
  scenePalette,
  sphere,
  textures,
  torus,
  type Animated,
  type CloudName,
  type ColorBy,
  type Point3,
  type SceneOptions,
  type Shape3d,
  type ShapeOptions as Shape3dOptions,
  type Shapes,
  type Texture,
  type TextureName,
} from "./shapes3d.ts";

// Particle systems: snow, rain, sparks, fireworks and systems of your own.
export {
  drawParticles,
  particles,
  particlesPalette,
  presets,
  streak,
  type Bounds,
  type BubblesOptions,
  type Direction,
  type DrawOptions as ParticlesDrawOptions,
  type Edge,
  type Emitter,
  type FirefliesOptions,
  type FireworksOptions,
  type MatrixOptions,
  type Particle,
  type ParticlesOptions,
  type Place,
  type PresetName,
  type PresetOptions,
  type RainOptions,
  type Range,
  type Scenery,
  type Size,
  type SnowOptions,
  type SparksOptions,
  type StarsOptions,
  type System,
  type Systems,
} from "./particles.ts";

// Effects that wrap any piece or text and return a new piece.
export {
  chain,
  dissolve,
  effect,
  fade,
  glint,
  glitch,
  hueCycle,
  hues,
  outline,
  outlines,
  rainbow,
  scan,
  shadow,
  shake,
  typeIn,
  wave,
  type DissolveOptions,
  type EffectDraw,
  type EffectSpec,
  type FadeOptions,
  type FxContext,
  type FxDraw,
  type FxMode,
  type FxOptions,
  type GlintOptions,
  type GlitchOptions,
  type OutlineOptions,
  type RainbowOptions,
  type ScanOptions,
  type ShadowOptions,
  type ShakeOptions,
  type TypeInOptions,
  type WaveOptions,
} from "./fx.ts";

// Pieces made of other pieces: layers, rows, grids, sequences and time.
export {
  border,
  column,
  crop,
  delay,
  flip,
  freeze,
  grid,
  layer,
  named,
  over,
  pad,
  repeat,
  row,
  scale,
  sequence,
  speed,
  type Anchor,
  type BorderOptions,
  type Clip,
  type ColumnOptions,
  type GridOptions,
  type Layer,
  type RowOptions,
  type SequenceOptions,
  type Side,
  type Step,
} from "./compose.ts";

// Any image as ascii.
export {
  drawImage,
  drawing,
  fromDrawing,
  fromImage,
  fromPixels,
  imagePalette,
  readPng,
  type DrawImageOptions,
  type Drawing,
  type ImageOptions,
  type ImagePiece,
  type ImageSource,
  type ImageStyle,
  type PixelArray,
  type PixelData,
} from "./image.ts";

// Objects built by saying what they are: shapes, materials, emissions and pictures.
export {
  area,
  ball,
  blob,
  bottle,
  box,
  bubbles,
  cellsOf,
  ceramic,
  cloud,
  cup,
  drawParts,
  edgeChar,
  emission,
  emit,
  fire,
  fish,
  flame,
  glass,
  gradientFill,
  grass,
  ground,
  heart,
  house,
  ice,
  inside,
  intersect,
  lamp,
  lava,
  leaf,
  material,
  metal,
  moon,
  mug,
  neon,
  palettes,
  partsPalette,
  pattern,
  patterns,
  picture,
  rain,
  sand,
  shape,
  sky,
  smoke,
  snow,
  solid,
  sparks,
  star,
  starfield,
  steam,
  straw,
  subtract,
  texture,
  union,
  water,
  waterGlass,
  wood,
  type Area,
  type Cells,
  type Cloud,
  type Colors,
  type Duo,
  type EdgeStyle,
  type Emission,
  type EmitOptions,
  type Emitted,
  type Fill,
  type House,
  type Lamp,
  type Material,
  type MaterialCell,
  type MaterialDraw,
  type MaterialOptions,
  type Move,
  type MoveFn,
  type Paint,
  type PaletteName,
  type Part,
  type PartOptions,
  type Placed,
  type Placement,
  type SizeWord,
  type Smoke,
  type SmokeOptions,
  type Spring,
  type TextureOptions,
  type Waves,
} from "./materials.ts";

// Any SVG as a piece, its parts brought to life by a map.
export {
  drawSvg,
  fromSvg,
  parseSvg,
  partCells,
  svgPalette,
  type DrawSvgOptions,
  type Motion,
  type Origin,
  type PartCells,
  type PartMaterial,
  type PartPaint,
  type Pose,
  type PoseFn,
  type Svg,
  type SvgMaterial,
  type SvgNode,
  type SvgPart,
  type SvgPartOptions,
  type SvgShape,
  type VectorOptions,
  type VectorStyle,
} from "./vector.ts";
