/*
 * ascii.rest/kit: tools for making ascii art of your own, as pieces that play
 * wherever the library's do. Part of ascii.rest by @bas3line
 * (https://github.com/bas3line), MIT licensed.
 *
 *   import { piece } from "ascii.rest/kit";
 */
export {
  EMPTY,
  INK,
  MAX,
  NONE,
  Palette,
  Surface,
  TAU,
  and,
  asPiece,
  bayer,
  checkMeta,
  clamp,
  code,
  fail,
  fract,
  gradient,
  hash,
  hex,
  isHex,
  lerp,
  mergePalettes,
  metaOf,
  mix,
  mulberry32,
  nearest,
  piece,
  ramp,
  ramps,
  rgb,
  sample,
  shadeChar,
  smoothstep,
  snapshot,
  specOf,
  spread,
  valueNoise,
  type Color,
  type Context,
  type Draw,
  type KitPiece,
  type MakerSpec,
  type PaletteSpec,
  type PieceSpec,
  type RampName,
  type Region,
  type Sampler,
  type Setup,
  type Source,
  type Themed,
} from "./core.ts";
