/*
 * ascii.rest/kit: tools for making ascii art of your own, as pieces that play
 * wherever the library's do. Recipes first, whole things in one line with no
 * maths; then the parts they are made of, for anything a recipe doesn't do.
 * Part of ascii.rest by @bas3line (https://github.com/bas3line), MIT licensed.
 *
 *   import { sea, spinning, torus } from "ascii.rest/kit";
 *
 *   export default sea({ palette: "ocean" });
 *   export const donut = spinning(torus(), { speed: "slow" });
 */

// Recipes: looks by name, motions in words, widgets in one call, placing by words, and palettes.
export { palette, schemeOf } from "./recipes/palettes.ts";
export {
  easings,
  loopFor,
  pieceOf,
  withLoop,
  type Amount,
  type Density,
  type Easing,
  type Heading,
  type Scale,
  type Speed,
  type Thing,
  type Toward,
} from "./recipes/words.ts";
export {
  Look,
  above,
  aurora,
  below,
  checker,
  clouds,
  flames,
  galaxy,
  lavaLamp,
  letters,
  look,
  marble,
  matrix,
  outside,
  plasma,
  plume,
  rainfall,
  rings,
  ripple,
  sea,
  snowfall,
  spiral,
  stars,
  stripes,
  sun,
  sweep,
  tunnel,
  turbulence,
  vortex,
  waves,
  type LookFn,
  type LookKit,
  type LookOptions,
  type LookRecipe,
  type Mask,
  type MaskLike,
} from "./recipes/looks.ts";
export {
  blinking,
  bouncing,
  drifting,
  floating,
  growIn,
  orbiting,
  planet,
  pulsing,
  shaking,
  slideIn,
  slideOut,
  spinning,
  swaying,
  type BlinkOptions,
  type BounceOptions,
  type DriftOptions,
  type EntranceOptions,
  type FloatOptions,
  type MotionOptions,
  type Offstage,
  type OrbitOptions,
  type PlanetOptions,
  type PulseOptions,
  type ShakingOptions,
  type SpinOptions,
  type SwayOptions,
  type Way,
  type World,
} from "./recipes/motion.ts";
export {
  across,
  at,
  barChart,
  card,
  clockFace,
  countdown,
  down,
  gauge,
  inset,
  marquee,
  panel,
  progressBar,
  ring,
  slot,
  sparkline,
  spinner,
  spinners,
  textAt,
  tiles,
  typewriter,
  type BarChartOptions,
  type CardOptions,
  type ClockFaceOptions,
  type CountdownOptions,
  type GaugeOptions,
  type MarqueeOptions,
  type PanelOptions,
  type ProgressBarOptions,
  type Room,
  type SparklineOptions,
  type SpinnerName,
  type SpinnerOptions,
  type TypewriterOptions,
} from "./recipes/widgets.ts";

// The grid, the piece() builder, colours, ramps and the maths every module shares.
export {
  EMPTY,
  INK,
  MAX,
  NONE,
  Palette,
  Surface,
  TAU,
  and,
  asPiece,
  bayer,
  checkMeta,
  clamp,
  code,
  colorOf,
  colorsOf,
  fail,
  fract,
  gradient,
  hash,
  hex,
  isHex,
  lerp,
  materialColors,
  mergePalettes,
  metaOf,
  mix,
  mulberry32,
  nearest,
  piece,
  ramp,
  ramps,
  rgb,
  sample,
  schemes,
  shadeChar,
  smoothstep,
  snapshot,
  specOf,
  spread,
  suggest,
  valueNoise,
  type Color,
  type ColorLike,
  type ColorName,
  type Context,
  type Draw,
  type KitPiece,
  type MakerSpec,
  type MaterialColorName,
  type PaletteLike,
  type PaletteSpec,
  type Scheme,
  type SchemeName,
  type PieceSpec,
  type RampName,
  type Region,
  type Sampler,
  type Setup,
  type Source,
  type Themed,
} from "./core.ts";

// Noise, randomness, easing, time and 3D maths.
export {
  camera,
  cycle,
  degrees,
  ease,
  fbm,
  fbm3,
  invLerp,
  lcm,
  loopNoise,
  mod,
  noise,
  noise2,
  noise3,
  noise4,
  oscillate,
  phase,
  pingpong,
  progress,
  project,
  pulse,
  radians,
  random,
  remap,
  ridged,
  rotate3,
  rotation,
  scatter,
  step,
  triangle,
  tween,
  twinkle,
  valueNoise3,
  vec2,
  vec3,
  worley,
  wrap,
  type Camera,
  type CameraOptions,
  type EaseName,
  type FbmOptions,
  type LoopNoiseOptions,
  type Noise,
  type NoiseKind,
  type NoiseOptions,
  type Projected,
  type Projection,
  type Random,
  type ScatterOptions,
  type Spot,
  type TweenOptions,
  type TwinkleOptions,
  type Vec2,
  type Vec3,
  type View,
  type WorleyOptions,
} from "./math.ts";

// Drawing on the grid: text, lines, boxes, shapes, stamps, braille and half-block canvases.
export {
  arc,
  around,
  boxes,
  braille,
  circle,
  ellipse,
  label,
  line,
  pixels,
  polygon,
  polyline,
  ray,
  rect,
  stamp,
  text,
  type Align,
  type BoxStyle,
  type Braille,
  type LineOptions,
  type Pixels,
  type PlotOptions,
  type Point,
  type PolygonOptions,
  type RectOptions,
  type ShapeOptions,
  type SpriteOptions,
  type StampOptions,
  type TextOptions,
  type VAlign,
} from "./draw.ts";

// Ascii art from a formula of x, y and t.
export { drawField, field, type FieldCell, type FieldFn, type FieldOptions, type FieldSpec } from "./field.ts";

// 3D scenes: shapes, a camera, light and textures.
export {
  cone,
  cube,
  cylinder,
  group,
  lines,
  mesh,
  orbit,
  parametric,
  plane,
  points,
  render3d,
  scene,
  scenePalette,
  sphere,
  textures,
  torus,
  type Angles,
  type Animated,
  type CloudName,
  type ColorBy,
  type Point3,
  type SceneOptions,
  type Shape3d,
  type ShapeOptions as Shape3dOptions,
  type Shapes,
  type Texture,
  type TextureName,
  type TurnName,
} from "./shapes3d.ts";

// Particle systems: snow, rain, sparks, fireworks and systems of your own.
export {
  drawParticles,
  particles,
  particlesPalette,
  presets,
  streak,
  system,
  type Bounds,
  type BubblesOptions,
  type Direction,
  type DrawOptions as ParticlesDrawOptions,
  type Edge,
  type Emitter,
  type FirefliesOptions,
  type FireworksOptions,
  type MatrixOptions,
  type Particle,
  type ParticlesOptions,
  type Place,
  type PresetName,
  type PresetOptions,
  type RainOptions,
  type Range,
  type Scenery,
  type Size,
  type SnowOptions,
  type SparksOptions,
  type StarsOptions,
  type System,
  type Systems,
} from "./particles.ts";

// Effects that wrap any piece or text and return a new piece.
export {
  chain,
  dissolve,
  effect,
  fade,
  glint,
  glitch,
  hueCycle,
  hues,
  outline,
  outlines,
  rainbow,
  scan,
  shadow,
  shake,
  typeIn,
  wave,
  type DissolveOptions,
  type EffectDraw,
  type EffectSpec,
  type FadeOptions,
  type FxContext,
  type FxDraw,
  type FxMode,
  type FxOptions,
  type GlintOptions,
  type GlitchOptions,
  type OutlineOptions,
  type RainbowOptions,
  type ScanOptions,
  type ShadowOptions,
  type ShakeOptions,
  type TypeInOptions,
  type WaveOptions,
} from "./fx.ts";

// Pieces made of other pieces: layers, rows, grids, sequences and time.
export {
  border,
  column,
  crop,
  delay,
  flip,
  freeze,
  grid,
  layer,
  named,
  over,
  pad,
  repeat,
  row,
  scale,
  sequence,
  speed,
  type Anchor,
  type BorderOptions,
  type Clip,
  type ColumnOptions,
  type GridOptions,
  type Layer,
  type RowOptions,
  type SequenceOptions,
  type Side,
  type Step,
} from "./compose.ts";

// Any image as ascii.
export {
  drawImage,
  drawing,
  fromDrawing,
  fromImage,
  fromPixels,
  imagePalette,
  readPng,
  type DrawImageOptions,
  type Drawing,
  type ImageOptions,
  type ImagePiece,
  type ImageSource,
  type ImageStyle,
  type PixelArray,
  type PixelData,
} from "./image.ts";

// Objects built by saying what they are: shapes, materials, emissions and pictures.
export {
  area,
  ball,
  blob,
  bottle,
  box,
  bubbles,
  cellsOf,
  ceramic,
  cloud,
  cup,
  drawParts,
  edgeChar,
  emission,
  emit,
  fire,
  fish,
  flame,
  glass,
  gradientFill,
  grass,
  ground,
  heart,
  house,
  ice,
  inside,
  intersect,
  lamp,
  lava,
  leaf,
  material,
  metal,
  moon,
  mug,
  neon,
  partsPalette,
  pattern,
  patterns,
  picture,
  rain,
  sand,
  shape,
  sky,
  smoke,
  snow,
  solid,
  sparks,
  star,
  starfield,
  steam,
  straw,
  subtract,
  texture,
  union,
  water,
  waterGlass,
  wood,
  type Area,
  type Cells,
  type Cloud,
  type Colors,
  type Duo,
  type EdgeStyle,
  type Emission,
  type EmitOptions,
  type Emitted,
  type Fill,
  type House,
  type Lamp,
  type Material,
  type MaterialCell,
  type MaterialDraw,
  type MaterialOptions,
  type Move,
  type MoveFn,
  type Paint,
  type PaletteName,
  type Part,
  type PartOptions,
  type Placed,
  type Placement,
  type SizeWord,
  type PointOn,
  type Smoke,
  type SmokeOptions,
  type Spring,
  type TextureOptions,
  type Waves,
} from "./materials.ts";

// Any SVG as a piece, its parts brought to life by a map.
export {
  drawSvg,
  fromSvg,
  parseSvg,
  partCells,
  svgPalette,
  type DrawSvgOptions,
  type Motion,
  type Origin,
  type PartCells,
  type PartMaterial,
  type PartPaint,
  type Pose,
  type PoseFn,
  type Svg,
  type SvgMaterial,
  type SvgNode,
  type SvgPart,
  type SvgPartOptions,
  type SvgShape,
  type VectorOptions,
  type VectorStyle,
} from "./vector.ts";
