// npm run gen: writes the two indexes of src/pieces after a piece is added or
// renamed. src/pieces/index.ts exports every piece by name for static imports;
// src/library.ts loads any piece by its file name on demand.
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { Piece } from "../src/types.ts";

const SRC = fileURLToPath(new URL("../src", import.meta.url));
const slugs = readdirSync(`${SRC}/pieces`)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .map((f) => f.slice(0, -3))
  .sort();
const camel = (slug: string) => slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
const HEAD =
  "// ascii.rest by @bas3line (https://github.com/bas3line), MIT licensed.\n" +
  "// Generated by scripts/gen.ts from the files in src/pieces. Run npm run gen after adding one.\n";

const canvas: string[] = [];
for (const slug of slugs) {
  const piece = (await import(pathToFileURL(`${SRC}/pieces/${slug}.ts`).href)) as Piece;
  if (piece.meta.palette) canvas.push(slug);
}

writeFileSync(
  `${SRC}/pieces/index.ts`,
  HEAD +
    `\n/** Every piece as a named export: import { donut, nightCoast } from "ascii.rest/pieces". */\n` +
    slugs.map((s) => `export * as ${camel(s)} from "./${s}.ts";\n`).join(""),
);

writeFileSync(
  `${SRC}/library.ts`,
  HEAD +
    `import type { Piece } from "./types.ts";\n\n` +
    `/** Every piece by file name, each loaded only when asked for, so bundlers give each its own chunk. */\n` +
    `export const load = {\n` +
    slugs.map((s) => `  ${JSON.stringify(s)}: () => import("./pieces/${s}.ts"),\n`).join("") +
    `} satisfies Record<string, () => Promise<Piece>>;\n\n` +
    `export type PieceName = keyof typeof load;\n\n` +
    `/** Every piece's file name. */\n` +
    `export const names = Object.keys(load) as PieceName[];\n\n` +
    `/** The coloured pieces, which draw on a <canvas> rather than a <pre>. */\n` +
    `export const canvas: ReadonlySet<PieceName> = new Set<PieceName>(${JSON.stringify(canvas)});\n\n` +
    `/** Whether a name is a piece in the library. */\n` +
    `export const isPiece = (name: string): name is PieceName => Object.hasOwn(load, name);\n`,
);
console.log(`${slugs.length} pieces, ${canvas.length} on a canvas`);
